# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#warnings_are_errors: true
r:
  - release
r_packages:
  - covr

sudo: required
#dist: trusty

# using renv with travis.ci
# https://rstudio.github.io/renv/articles/ci.html

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

# turn off checking of packages in DESCRIPTION suggests
env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: false

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

#script:
#  - nohup R --slave --no-restore -e 'shiny::runApp(port = 3000)' &

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
