# Derived from https://github.com/miraisolutions/ShinyCICD/blob/master/.github/workflows/ci-cd-renv.yml
# and https://github.com/r-lib/actions/tree/v2/examples

on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      # We keep a matrix for convenience, but we would typically just run on one
      # single OS and R version, aligned with the target deployment environment
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macos-latest,   r: 'release'}
          # shinyapps.io uses ubuntu-20.04 instead of ubuntu-latest
          # https://docs.posit.co/shinyapps.io/appendix.html#default-system-packages
          - {os: ubuntu-20.04,  r: 'release'}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(pkgs = c("devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: devtools::check(error_on = "error")
        shell: Rscript {0}
